// 40 resume glossary terms
// Each entry: slug, term, short (meta), definition (first para), detail (second para), example (optional), related (slugs)
module.exports = [
  {
    slug: "ats",
    term: "ATS (Applicant Tracking System)",
    short: "An ATS is software companies use to filter resumes before a human reads them.",
    definition: "An Applicant Tracking System (ATS) is a software platform that employers use to collect, sort, and rank job applications. When you submit a resume through an online job portal, it rarely goes directly to a recruiter — it's parsed by an ATS that extracts your contact info, work history, and skills into structured data, then scores your resume against the job description.",
    detail: "Roughly 75% of resumes are filtered out by ATS before a human reviewer ever opens them. Common ATS platforms include Workday, Greenhouse, Lever, Taleo, and iCIMS. Each has slightly different parsing rules, but they all struggle with non-standard formatting — tables, two-column layouts, images, headers/footers, and fancy fonts. An ATS-friendly resume uses clean single-column formatting, standard section headings, and keywords from the job description.",
    example: "If the job says \"customer relationship management,\" your resume should contain that exact phrase — not just \"managed customer accounts.\" The ATS is scanning for the literal string.",
    related: ["keywords", "resume-parsing", "ats-friendly-resume", "hard-skills"],
  },
  {
    slug: "action-verb",
    term: "Action Verb",
    short: "A strong verb that starts a resume bullet and describes what you did.",
    definition: "An action verb is a powerful, specific verb used at the start of a resume bullet point to describe a concrete achievement. Strong action verbs imply ownership and capability (e.g., \"Launched,\" \"Negotiated,\" \"Optimized\"), while weak alternatives like \"Helped with\" or \"Responsible for\" sound passive and generic.",
    detail: "The verb is the most important word in any bullet point because it tells the reader what <em>you</em> actually did. Using 185+ distinct action verbs across your resume keeps the writing fresh and specific. Good verbs often come in categories: leadership (Led, Directed), building (Built, Engineered), improvement (Optimized, Streamlined), and growth (Grew, Scaled).",
    example: "Instead of \"Responsible for social media accounts,\" write \"Launched and scaled brand TikTok from 0 to 48,000 followers in 11 months.\"",
    related: ["bullet-point", "quantifiable-achievement", "power-words", "responsible-for"],
  },
  {
    slug: "ats-friendly-resume",
    term: "ATS-Friendly Resume",
    short: "A resume formatted so that Applicant Tracking Systems can parse it correctly.",
    definition: "An ATS-friendly resume is one that's been formatted to parse cleanly through Applicant Tracking Systems — the software most mid-to-large companies use to filter applications. It uses standard section headings, a single-column layout, simple bullet points, and keyword-matched content from the job description.",
    detail: "The key principles: avoid tables, text boxes, images, headers/footers, and decorative fonts. Use standard section names like \"Experience,\" \"Education,\" and \"Skills\" (not \"My Journey\" or \"Where I've Worked\"). Export as a text-based PDF so the ATS can select the text. Use keywords from the job description verbatim, without stuffing. Most importantly, write in the same language the ATS is scanning for.",
    example: "A resume with two columns and a profile photo might look beautiful to a human but get scrambled by an ATS. A single-column layout with no graphics parses cleanly every time.",
    related: ["ats", "keywords", "resume-parsing", "pdf-resume"],
  },
  {
    slug: "bullet-point",
    term: "Bullet Point",
    short: "A single line in your work experience describing one specific achievement.",
    definition: "A bullet point is a single line or sentence in the work experience section of your resume that describes one specific task, responsibility, or achievement. Modern resumes use bullet points instead of paragraphs because they're easier to scan and force you to be concise.",
    detail: "A strong bullet point follows the <strong>action verb + task + result</strong> formula. Each bullet should be one to two lines long. Most jobs warrant 3 to 6 bullets; older or less relevant jobs can have fewer. Every bullet should add new information — don't repeat what's already obvious from your job title.",
    example: "Bad: \"Managed the team.\" Good: \"Led a 6-person engineering team to ship a new reporting feature used by 12,000 monthly active users within 3 months.\"",
    related: ["action-verb", "quantifiable-achievement", "work-experience"],
  },
  {
    slug: "career-gap",
    term: "Career Gap",
    short: "A period of unemployment or time away from work visible on your resume.",
    definition: "A career gap (also called an employment gap) is any period longer than a few months where you were not formally employed. Gaps can be intentional (childcare, travel, education, health, sabbatical) or unintentional (layoffs, extended job searches). They're increasingly common and no longer carry the stigma they once did.",
    detail: "The best way to handle a gap is to be honest and brief. Don't try to hide it with a functional resume format — recruiters will spot the trick and become suspicious. Instead, acknowledge the gap directly, either in your cover letter or with a short \"Career Break\" line on the resume explaining what you did during it (learning, caregiving, freelance, etc.). Keeping your skills current during the gap is the most important thing you can do.",
    example: "A line like \"Career Break (2024–2026): Full-time caregiving for family; completed Google UX Certificate and shipped 3 portfolio projects\" turns a gap into a story.",
    related: ["functional-resume", "professional-summary", "cover-letter"],
  },
  {
    slug: "chronological-resume",
    term: "Chronological Resume",
    short: "The standard resume format, listing jobs from most recent to oldest.",
    definition: "A chronological resume (or reverse-chronological resume) lists your work experience in order from your most recent job to your oldest. It's the most common format — about 95% of resumes should use this structure — because recruiters expect it, ATS parsers handle it cleanly, and it tells a clear career story.",
    detail: "In a chronological resume, your most recent and relevant experience appears at the top. The format assumes your career has been progressing, so the reader's eye naturally lands on your peak first. Each job includes a title, company, location, dates, and 3 to 6 bullet points of specific achievements. Older jobs (10+ years back) can be summarized into a short \"Earlier Experience\" line.",
    example: "A software engineer's resume might show: Senior Engineer @ Acme (2024–Present), Engineer @ Foo Inc (2021–2024), Junior Engineer @ Bar Co (2019–2021) — each with bullet points underneath.",
    related: ["functional-resume", "combination-resume", "reverse-chronological", "work-experience"],
  },
  {
    slug: "combination-resume",
    term: "Combination Resume",
    short: "A hybrid format that leads with skills but still lists jobs chronologically.",
    definition: "A combination resume (also called a hybrid resume) merges the structure of a chronological resume with the skill-focus of a functional resume. It starts with an expanded skills section at the top, grouped into categories, then follows with a traditional reverse-chronological work experience section.",
    detail: "This format is useful when you're changing careers and want to lead with transferable skills, or when your technical skills deserve prominent placement. Unlike a pure functional resume, it doesn't hide your employment history — which means it doesn't trigger the \"what is this person hiding?\" reflex that recruiters have with pure functional resumes.",
    example: "A teacher transitioning to UX design might lead with a \"Design Skills\" section (Figma, user research, prototyping) before the \"Experience\" section, so recruiters see the relevant capability first.",
    related: ["chronological-resume", "functional-resume", "resume-format"],
  },
  {
    slug: "cover-letter",
    term: "Cover Letter",
    short: "A one-page letter sent with your resume explaining why you're applying.",
    definition: "A cover letter is a one-page document that accompanies your resume when you apply for a job. Its purpose is to explain, in your own voice, why you're interested in this specific role, what makes you a strong fit, and what you hope to bring. Unlike a resume, it's written in prose and can show personality.",
    detail: "Not every job requires a cover letter, and some recruiters never read them. But when they're required, a strong cover letter can tip the scales in your favor. The structure: a specific hook in the first paragraph (not \"I am writing to apply for...\"), two middle paragraphs showing relevant experience with concrete examples, and a closing paragraph that's warm and direct about next steps.",
    example: "Open with something like: \"When I read your job posting yesterday, I immediately thought of the retention problem I solved at my last company — because it sounds exactly like what you're describing.\"",
    related: ["resume", "professional-summary", "career-change"],
  },
  {
    slug: "cv",
    term: "CV (Curriculum Vitae)",
    short: "In the US, a long academic document. Outside the US, often the same as a resume.",
    definition: "\"CV\" is short for <em>curriculum vitae</em>, Latin for \"course of life.\" In the US and Canada, a CV means a comprehensive academic or medical document that can run 10+ pages and lists every publication, presentation, grant, and teaching assignment. In the rest of the world — the UK, Europe, Australia, India — \"CV\" is simply what Americans call a resume: a 1-2 page tailored document.",
    detail: "If you're in the US or Canada applying for a non-academic job, you almost certainly need a resume, not a CV, even if the job posting uses the word \"CV.\" If you're in the UK, Europe, or elsewhere, \"CV\" is the standard term for a short resume-style document. Always check your country's convention and the specific employer's expectation.",
    example: "An American professor applying for tenure needs a 12-page CV. A British marketing manager applying for a job at a London agency needs a 2-page CV (which is the same format as an American resume).",
    related: ["resume", "chronological-resume", "resume-vs-cv"],
  },
  {
    slug: "education-section",
    term: "Education Section",
    short: "The section of your resume listing your degrees and schools.",
    definition: "The Education section of a resume lists your formal academic qualifications: degrees, schools, graduation years, and sometimes honors or coursework. For most professionals with work experience, this section is short and sits near the bottom. For recent graduates, it moves up near the top because it's the most relevant credential.",
    detail: "Include your degree (e.g., \"Bachelor of Science in Computer Science\"), school name, and graduation year. Add your GPA only if it's 3.5 or higher, and only in your first three years out of school. Don't include high school once you're past your first semester of college. If you haven't finished a degree, you can list it as \"Coursework in [field]\" or specify your expected graduation date.",
    example: "\"Bachelor of Arts in Economics, University of Michigan, 2024 (GPA 3.7, Dean's List)\"",
    related: ["resume-with-no-experience", "relevant-coursework"],
  },
  {
    slug: "employment-gap",
    term: "Employment Gap",
    short: "Another term for a career gap — a break in your work history.",
    definition: "An employment gap is a period of time — usually six months or longer — where you were not employed. Gaps can happen for many reasons: layoffs, caregiving, health, education, sabbatical, travel, or career change. Despite old advice to the contrary, employment gaps are common and don't automatically hurt your application.",
    detail: "The best strategy for handling gaps is transparency. Don't try to disguise them with a functional resume format — recruiters know the trick. Instead, briefly explain the gap either on your resume, in your cover letter, or in the interview. If you kept your skills current during the gap (online courses, freelance work, volunteering), mention it.",
    example: "A gap explained well: \"Career Break (2023–2025): Cared for family member; completed AWS Certified Cloud Practitioner; contributed to 2 open-source projects.\"",
    related: ["career-gap", "functional-resume", "cover-letter"],
  },
  {
    slug: "executive-summary",
    term: "Executive Summary",
    short: "A senior-level version of the professional summary, used by directors and VPs.",
    definition: "An executive summary is the summary section at the top of a senior-level resume. It's typically slightly longer than a standard professional summary (3 to 5 sentences instead of 2 to 3) and focuses on leadership scope, business impact, and specialized expertise rather than individual contributor achievements.",
    detail: "A good executive summary mentions your title, years of experience, industry or domain, the size of teams or budgets you've managed, and at least one transformative outcome. It should read like a pitch to the board, not a personal introduction. Avoid buzzwords; focus on specific, verifiable accomplishments.",
    example: "\"Chief Marketing Officer with 15+ years scaling B2B SaaS brands from Series A to IPO. Built and led a 60-person global marketing organization at Acme Corp, driving $80M in pipeline annually and taking the brand to a Gartner Magic Quadrant leader position in 3 years.\"",
    related: ["professional-summary", "c-suite-resume"],
  },
  {
    slug: "functional-resume",
    term: "Functional Resume",
    short: "A skills-focused format that downplays work history. Usually a bad idea.",
    definition: "A functional resume organizes your content around skill categories rather than job history. Instead of listing each job with bullet points underneath, a functional resume groups achievements under headings like \"Leadership,\" \"Project Management,\" and \"Technical Skills.\" Employment history appears as a short list of companies and dates, with no bullet points.",
    detail: "Functional resumes have a bad reputation — deservedly. Recruiters see them as red flags because they're typically used to hide employment gaps, short tenures, or a lack of relevant experience. ATS parsers also struggle with functional resumes because they can't correctly associate achievements with specific jobs. Unless you're in a specific field where functional resumes are the literal standard, avoid this format.",
    example: "Under \"Project Management,\" a functional resume might list: \"Led cross-functional initiatives across engineering, design, and marketing teams\" — but without context about which job or when, the bullet carries no weight.",
    related: ["chronological-resume", "combination-resume", "resume-format"],
  },
  {
    slug: "hard-skills",
    term: "Hard Skills",
    short: "Teachable, measurable technical skills like languages or software.",
    definition: "Hard skills are specific, teachable, and measurable technical abilities — things like programming languages, software tools, methodologies, languages spoken, and certifications. They're contrasted with \"soft skills\" (interpersonal qualities like communication and teamwork) and are usually the skills a job description explicitly lists as required.",
    detail: "Examples of hard skills include: Python, SQL, Figma, Salesforce, Excel, Google Analytics, Adobe Photoshop, Spanish (C1 level), AWS certifications, financial modeling, and SEO. On a resume, hard skills belong in a dedicated Skills section and should also appear in your bullet points showing how you applied them.",
    example: "A software engineer's hard skills: \"Python, TypeScript, React, PostgreSQL, AWS, Docker, GraphQL.\" A marketer's: \"Google Analytics, HubSpot, SEMrush, Meta Ads, Figma, SQL.\"",
    related: ["soft-skills", "skills", "ats", "keywords"],
  },
  {
    slug: "hiring-manager",
    term: "Hiring Manager",
    short: "The person who will be your future boss — the one deciding who to hire.",
    definition: "A hiring manager is the person directly responsible for filling a specific role, usually the future boss of whoever gets hired. They're the one who writes or approves the job description, interviews candidates, and makes the final hiring decision. Hiring managers are distinct from recruiters (who source candidates) and HR (who handle the paperwork).",
    detail: "When you're tailoring your resume or cover letter, you're really writing for the hiring manager — not the ATS, not the recruiter, not HR. Understanding what this person cares about (What does their team struggle with? What would make their job easier?) helps you emphasize the right experience and skills.",
    example: "If you're applying for a Senior Software Engineer role, the hiring manager is probably the Engineering Manager you'd report to. If you're applying for Marketing Director, the hiring manager might be the CMO or the CEO.",
    related: ["recruiter", "cover-letter", "tailoring"],
  },
  {
    slug: "keywords",
    term: "Keywords",
    short: "Specific terms from a job description that must appear on your resume.",
    definition: "Keywords are specific words or phrases from a job description that an Applicant Tracking System scans for when ranking resumes. They typically include the required skills, tools, certifications, and job title variations the employer is looking for. Matching keywords to your resume is the single biggest lever for getting past the ATS filter.",
    detail: "To find the right keywords, read the job description carefully and highlight every skill, tool, methodology, and qualification mentioned. For every keyword you honestly have experience with, make sure it appears verbatim somewhere on your resume — in your summary, skills section, or bullet points. Don't exaggerate, and don't keyword-stuff (listing every keyword 10 times). Modern ATS catch that and modern recruiters see through it.",
    example: "If the job requires \"A/B testing,\" write \"A/B testing\" on your resume — not \"experiment design\" or \"split testing.\" The ATS is looking for the literal phrase.",
    related: ["ats", "ats-friendly-resume", "tailoring", "hard-skills"],
  },
  {
    slug: "ksa",
    term: "KSA (Knowledge, Skills, Abilities)",
    short: "A framework used primarily in government job applications to show qualifications.",
    definition: "KSA stands for Knowledge, Skills, and Abilities — a three-part framework commonly used in US federal government job applications on USAJobs. Each KSA statement is a short paragraph explaining how your experience meets a specific required qualification.",
    detail: "Private-sector job seekers don't usually write KSA statements — they write a normal resume with bullet points. But for federal jobs, you'll often need to submit KSAs as a separate document or as narrative answers within the USAJobs application. Each KSA should be specific, measurable, and tied to concrete examples.",
    example: "A KSA for \"Ability to manage complex projects\" might read: \"Managed a $2.4M agency rebranding project involving 5 contractors and 3 internal teams, delivered on time and 8% under budget.\"",
    related: ["federal-resume", "cover-letter"],
  },
  {
    slug: "linkedin-url",
    term: "LinkedIn URL",
    short: "Your LinkedIn profile address — and it should always be on your resume.",
    definition: "A LinkedIn URL is the direct web address of your LinkedIn profile. Adding it to your resume has become standard practice because recruiters use LinkedIn to verify your background, see recommendations, and learn more about you beyond what fits on a one-page resume.",
    detail: "Before adding it to your resume, customize your LinkedIn URL so it's clean and memorable: by default, LinkedIn gives you a URL like <code>linkedin.com/in/jane-smith-12a34b5</code>, but you can change this to <code>linkedin.com/in/janesmith</code> for free in your settings. Make sure your LinkedIn profile is up to date and consistent with your resume before listing it.",
    example: "In your resume header, list it simply: \"linkedin.com/in/janesmith\" — no https://, no www.",
    related: ["header", "contact-info", "portfolio"],
  },
  {
    slug: "margin",
    term: "Margin",
    short: "The empty space around the edge of your resume. Between 0.5 and 1 inch is ideal.",
    definition: "Margins are the blank space around the edges of your resume, framing the content. Standard resume margins are 0.5 to 1 inch on all sides. Tighter margins (0.5 inch) let you fit more content; wider margins (1 inch) look more breathable but leave less space.",
    detail: "Never go below 0.5 inch — margins smaller than that make the resume feel cramped and hard to read. If your content is overflowing, don't shrink the margins; cut weaker content instead. Conversely, if you're filling less than half a page, widening margins is a lazy fix — add more substance.",
    example: "A one-page resume with 0.75-inch margins strikes the best balance for most professionals: readable, professional, and fits standard content comfortably.",
    related: ["one-page-resume", "white-space", "resume-length"],
  },
  {
    slug: "objective-statement",
    term: "Objective Statement",
    short: "An outdated resume section focused on what you want. Replace with a summary.",
    definition: "An objective statement is a short paragraph at the top of a resume that describes what kind of job the candidate is seeking. It was standard resume practice until the early 2010s but has since been almost entirely replaced by the professional summary, which focuses on what you <em>bring</em> rather than what you <em>want</em>.",
    detail: "Hiring managers know what you want — a job. What they don't know is whether you're the right person for it. A professional summary answers that question; an objective doesn't. If your resume still has an objective statement, replace it immediately with a summary.",
    example: "Delete: \"Seeking a challenging role in a dynamic company where I can leverage my skills.\" Replace with: \"Product Manager with 6 years scaling B2B SaaS from $2M to $18M ARR through discovery, A/B testing, and cross-functional leadership.\"",
    related: ["professional-summary", "header"],
  },
  {
    slug: "one-page-resume",
    term: "One-Page Resume",
    short: "A resume that fits on a single page. The standard for most professionals.",
    definition: "A one-page resume is a resume that fits entirely on one side of a single sheet of paper (A4 or US Letter). For professionals with less than 10 years of experience, one page is the standard — and often the expectation. One-page resumes force you to edit aggressively and keep only your strongest material.",
    detail: "Recruiters spend an average of 6 to 8 seconds on their first scan of a resume. A one-page document respects that time constraint and makes your strongest points impossible to miss. If you have more than 10 years of experience, a two-page resume is acceptable, but anything longer than that is almost always a sign of padding.",
    example: "A software engineer with 7 years of experience should have a one-page resume. A VP with 18 years of experience can use two pages — but still shouldn't go to three.",
    related: ["resume-length", "two-page-resume", "margin"],
  },
  {
    slug: "pdf-resume",
    term: "PDF Resume",
    short: "A resume exported as a PDF file. Always preferred over Word documents.",
    definition: "A PDF resume is a resume saved in Portable Document Format — the standard file type for sharing resumes in 2026. PDFs preserve your formatting perfectly across devices and operating systems, unlike Word documents, which render differently depending on which version of which software opens them.",
    detail: "The old advice that ATS couldn't read PDFs is outdated. All modern ATS parse text-based PDFs correctly. The only time to use a Word document is when a specific application explicitly requires .docx — and even then, only if the system won't accept PDFs. Never submit an image file (JPG or PNG) of your resume; ATS can't read those at all.",
    example: "Export your resume as a text-based PDF with a filename like <code>jane-smith-resume.pdf</code>, not <code>resume_final_v3.docx</code>.",
    related: ["ats-friendly-resume", "resume-parsing", "file-format"],
  },
  {
    slug: "portfolio",
    term: "Portfolio",
    short: "A collection of your work samples. Common for designers, developers, and writers.",
    definition: "A portfolio is a curated collection of work samples that demonstrates your skills and experience in practice. Designers show visual work, developers show code projects, writers show published pieces, and marketers show campaigns or case studies. A portfolio supplements a resume — it doesn't replace it.",
    detail: "In some fields (graphic design, UX design, front-end development, writing, photography), a portfolio is as important as the resume. In others (accounting, medicine, law, sales), portfolios aren't a thing. If a portfolio applies to your field, host it on a simple personal website or platform (Dribbble, Behance, GitHub) and include a link in your resume header.",
    example: "A UX designer's portfolio might include 3 to 5 case studies, each showing the problem, process, and outcome of a real project.",
    related: ["linkedin-url", "projects", "header"],
  },
  {
    slug: "power-words",
    term: "Power Words",
    short: "Strong action verbs that make your resume more specific and memorable.",
    definition: "Power words are strong, specific verbs and phrases that make a resume sound active, confident, and specific. They're usually contrasted with weak filler words like \"responsible for,\" \"helped with,\" or \"assisted.\" Using power words turns vague bullet points into memorable achievements.",
    detail: "Power words are most effective when paired with a measurable outcome. \"Spearheaded\" is a power word, but \"Spearheaded a cross-functional initiative that reduced customer churn from 12% to 4% in 18 months\" is what actually impresses recruiters. Use variety — don't repeat the same verb more than twice across your resume.",
    example: "Instead of \"Worked on product launches,\" try \"Orchestrated four major product launches totaling $4.2M in first-year revenue.\"",
    related: ["action-verb", "bullet-point", "quantifiable-achievement"],
  },
  {
    slug: "professional-summary",
    term: "Professional Summary",
    short: "A 2-4 sentence paragraph at the top of your resume summarizing who you are.",
    definition: "A professional summary (also called a resume summary, career summary, or profile statement) is a short paragraph at the top of your resume — below your contact info — that introduces who you are professionally, what you're good at, and what you bring. It's the first real content a recruiter reads.",
    detail: "A good summary is 2 to 4 sentences long and includes: your job title and years of experience, your top 2 or 3 specialized skills, and at least one measurable achievement or unique credential. Avoid buzzwords like \"hard-working\" or \"motivated\" — they mean nothing. Instead, be specific about what you've actually done.",
    example: "\"Senior Software Engineer with 7 years building scalable backend systems in Go and Python. Led the migration of a 2M-user monolith to microservices at Acme Corp, cutting API latency by 60%.\"",
    related: ["objective-statement", "executive-summary", "header"],
  },
  {
    slug: "quantifiable-achievement",
    term: "Quantifiable Achievement",
    short: "A resume bullet that includes a specific number or measurable result.",
    definition: "A quantifiable achievement is a resume bullet point that includes a specific, measurable result — a number, percentage, dollar amount, time saved, or comparative metric. Quantified bullets are 10x more memorable than unquantified ones because they give the reader a concrete reference point.",
    detail: "Every resume should have at least one quantified bullet per job, and ideally 2 to 3. Metrics come in many forms: scale (team size, audience size), frequency (weekly, daily), money (revenue, savings, budget), time (hours saved, time reduction), percentages (growth, retention), and rankings (#1 out of 18). Even when you don't have \"official\" metrics, you can usually estimate.",
    example: "Weak: \"Grew the email list.\" Strong: \"Grew the email list from 3,200 to 18,400 subscribers in 9 months through a weekly newsletter and a lead-magnet campaign.\"",
    related: ["bullet-point", "action-verb", "power-words"],
  },
  {
    slug: "recruiter",
    term: "Recruiter",
    short: "The person (internal or external) who sources and screens candidates.",
    definition: "A recruiter is a person who finds and screens candidates for open jobs. Recruiters can be internal (employed by the company doing the hiring) or external (working at a staffing agency or headhunting firm). They're typically the first human to see your resume, and their job is to pass the most promising candidates to the hiring manager.",
    detail: "Recruiters spend an average of 6 to 8 seconds on their first scan of a resume. They're not reading carefully; they're looking for pattern matches against the job requirements. That's why clarity, keyword matching, and a strong summary matter so much. A good first impression gets a second, deeper read.",
    example: "A senior recruiter at a tech company might review 50 to 200 resumes per day during active hiring. Your resume has to stand out in a pile, fast.",
    related: ["hiring-manager", "ats", "tailoring"],
  },
  {
    slug: "references",
    term: "References",
    short: "People who can vouch for your work. Don't list them on your resume.",
    definition: "References are people — former managers, colleagues, professors, or clients — who can vouch for your professional skills and character. Employers typically ask for references near the end of the hiring process, after they've decided you're a strong candidate but before making an offer.",
    detail: "Don't put references on your resume. Don't even write \"References available on request\" — it's outdated and wastes a line. Instead, prepare a separate document with 3 to 5 references (name, title, company, email, phone, and how they know you) and send it when asked. Always ask permission from your references before listing them, and give them a heads-up when you're actively job hunting.",
    example: "A reference document has one reference per block: \"Sarah Johnson, Senior Director of Engineering at Acme Corp. sarah@acme.com / (555) 123-4567. Former manager, 2022-2024.\"",
    related: ["cover-letter", "linkedin-url"],
  },
  {
    slug: "resume",
    term: "Resume",
    short: "A 1-2 page document summarizing your work history, skills, and qualifications.",
    definition: "A resume is a short document — usually 1 to 2 pages — that summarizes your professional experience, skills, education, and qualifications for the purpose of applying to jobs. Standard sections include a header with contact info, a professional summary, work experience, education, and skills.",
    detail: "In the US and Canada, \"resume\" is the default term for this document. In the UK, Europe, and most of the rest of the world, the same document is called a \"CV.\" Either way, a good resume is tailored to the specific job, uses reverse-chronological order, and focuses on measurable achievements rather than generic job descriptions.",
    example: "A typical resume has 5 sections: Header (name + contact), Professional Summary (2-4 sentences), Work Experience (reverse chronological), Education, and Skills.",
    related: ["cv", "chronological-resume", "professional-summary"],
  },
  {
    slug: "resume-builder",
    term: "Resume Builder",
    short: "An online tool that helps you create a resume using pre-designed templates.",
    definition: "A resume builder is an online tool that helps job seekers create a professional resume without starting from a blank Word document. Good resume builders offer pre-designed templates, section-by-section guidance, real-time preview, and one-click PDF export.",
    detail: "Not all resume builders are genuinely free. Many use a dark pattern: you fill in all your information for free, then hit a paywall at the download step. The few that are truly free either ask for an account, add a watermark, or limit your exports. Resume88 is an exception — no signup, no credit card, no watermark, unlimited exports, and the code is open source.",
    example: "A good resume builder lets you pick a template, fill in your information, see a live preview, and export a clean PDF — all without paying.",
    related: ["pdf-resume", "template", "cover-letter"],
  },
  {
    slug: "reverse-chronological",
    term: "Reverse Chronological",
    short: "A resume format that lists jobs from most recent to oldest. The standard.",
    definition: "Reverse chronological is the standard resume ordering: most recent job first, older jobs following. It's the format 95% of resumes should use because it's familiar to recruiters, parses cleanly in ATS, and tells a clear career progression story.",
    detail: "In a reverse chronological resume, each job includes a title, company, location, dates, and 3 to 6 bullet points describing your specific achievements. Your most recent job gets the most space because it's the most relevant to hiring decisions. Older jobs (10+ years back) can be consolidated into a short \"Earlier Experience\" line.",
    example: "Order: Senior Engineer (2024–Present), Engineer (2021–2024), Junior Engineer (2019–2021). Not: Junior Engineer first.",
    related: ["chronological-resume", "functional-resume", "work-experience"],
  },
  {
    slug: "soft-skills",
    term: "Soft Skills",
    short: "Interpersonal qualities like communication and leadership. Hard to prove on paper.",
    definition: "Soft skills are interpersonal and behavioral qualities — things like communication, leadership, teamwork, problem-solving, adaptability, and emotional intelligence. They contrast with \"hard skills,\" which are specific technical abilities like coding languages or software tools.",
    detail: "Soft skills are genuinely important for most jobs, but they're hard to prove on a resume because every candidate claims to have them. Instead of listing soft skills in a dedicated section, demonstrate them through your achievement bullets. If you led a cross-functional team that shipped a product, that's leadership — shown, not stated.",
    example: "Don't write \"strong communicator.\" Do write \"Led weekly executive updates on a $3M product launch, keeping 4 cross-functional teams and 12 stakeholders aligned.\"",
    related: ["hard-skills", "bullet-point", "action-verb"],
  },
  {
    slug: "tailoring",
    term: "Tailoring (a Resume)",
    short: "Customizing your resume for each specific job application.",
    definition: "Tailoring a resume means adjusting its content — especially the summary, skills section, and bullet points — to match the specific job you're applying for. Tailored resumes use the exact language from the job description and emphasize the most relevant experience, while de-emphasizing unrelated material.",
    detail: "Tailoring is the single highest-leverage activity in a job search. A generic resume sent to 50 jobs typically gets fewer interviews than a tailored resume sent to 5 jobs. The reason is simple: Applicant Tracking Systems score resumes by keyword match against the job description, and recruiters are scanning for role-relevant experience. Tailoring aligns with both.",
    example: "For a product manager role that emphasizes A/B testing, you'd rewrite your summary to include \"A/B testing\" and promote bullets about experimentation to the top.",
    related: ["keywords", "ats", "professional-summary"],
  },
  {
    slug: "template",
    term: "Template (Resume)",
    short: "A pre-designed resume layout you can fill in with your information.",
    definition: "A resume template is a pre-designed layout — fonts, spacing, colors, structure — that you fill in with your own content. Templates save you from formatting from scratch and ensure your resume looks professional. They come in many styles: classic, modern, minimal, creative, corporate, and so on.",
    detail: "The best resume templates are ATS-friendly (single-column, standard fonts, no tables or text boxes) and subtle in design — they support your content without stealing attention from it. Avoid templates with colorful sidebars, skill bars, or graphic elements if you're applying to corporate roles; save those for creative industries.",
    example: "Resume88 offers 6 free templates: Classic, Modern, Minimal, Corporate, Creative, and Sidebar. All are ATS-tested and work in 8 color themes.",
    related: ["ats-friendly-resume", "resume-builder", "pdf-resume"],
  },
  {
    slug: "transferable-skills",
    term: "Transferable Skills",
    short: "Skills from one career or field that apply directly to another.",
    definition: "Transferable skills are abilities you've developed in one context (a job, a volunteer role, a degree program) that apply in a different context. They're especially important for career changers, recent graduates, and anyone returning to the workforce after a break.",
    detail: "Common transferable skills include: project management, analytical thinking, written and verbal communication, budgeting, people management, teaching, data analysis, and customer relationship building. When you're making a career transition, frame your past experience in terms of these transferable skills rather than the specific tools or titles of your old field.",
    example: "A teacher transitioning to corporate training might highlight: lesson planning (instructional design), classroom management (facilitation), curriculum development (content strategy), and student assessment (learning measurement).",
    related: ["career-change", "combination-resume", "soft-skills"],
  },
  {
    slug: "white-space",
    term: "White Space",
    short: "The blank space on your resume. Makes content scannable and professional.",
    definition: "White space refers to the empty, unprinted areas of your resume — the margins, the gaps between sections, the space between lines. Despite the name, it doesn't have to be white; it's any area without text or graphics. White space is what makes a resume scannable and comfortable to read.",
    detail: "A resume crammed with text from edge to edge is exhausting to scan. Good resumes use white space intentionally: margins of 0.5 to 1 inch, line spacing of 1.0 to 1.15, a visible gap between each section, and bullet points instead of paragraphs. If your resume feels cluttered, you usually have too much content, not too little space.",
    example: "Compare two resumes with identical text: one with tight 0.3-inch margins and no section gaps, one with 0.75-inch margins and breathing room between sections. The second gets read; the first gets skipped.",
    related: ["margin", "one-page-resume", "resume-format"],
  },
  {
    slug: "work-experience",
    term: "Work Experience",
    short: "The section listing your past jobs, with bullet points describing each.",
    definition: "The Work Experience section (also called \"Experience\" or \"Employment\") is the main body of a resume. It lists your past jobs in reverse chronological order, with 3 to 6 bullet points under each job describing your specific achievements. For most professionals, this is the most important section of the resume.",
    detail: "Each work experience entry should include: job title, company name, location, dates of employment, and bullet points. The bullets should use the action verb + task + measurable result formula, and most of them should be quantified. Don't write job descriptions — write specific achievements that prove your impact.",
    example: "\"Senior Marketing Manager — Acme Corp, San Francisco, CA (Jan 2023 – Present). • Grew organic traffic 340% in 18 months through a content program I built from scratch.\"",
    related: ["bullet-point", "action-verb", "chronological-resume"],
  },
  {
    slug: "header",
    term: "Header (Resume)",
    short: "The top section of your resume with name, title, and contact information.",
    definition: "The header of a resume is the top block containing your name, professional title, and contact information (email, phone, location, LinkedIn, and optionally a portfolio URL). It's the first thing a recruiter sees and should make it effortless to identify and reach you.",
    detail: "Keep your header simple. Your full name goes in the biggest font — 18 to 24pt. Underneath, list your professional title (e.g., \"Software Engineer,\" not \"Job Seeker\"). Below that, a single line with your essential contact info. Don't include your full street address, date of birth, marital status, or a photo (at least in the US, UK, Canada, and Australia — photos are standard in parts of continental Europe).",
    example: "Header example: \"Jane Smith / Senior Software Engineer / jane@email.com · (555) 123-4567 · San Francisco, CA · linkedin.com/in/janesmith · github.com/janesmith\"",
    related: ["linkedin-url", "professional-summary", "contact-info"],
  },
  {
    slug: "resume-length",
    term: "Resume Length",
    short: "How long your resume should be. Usually one page, sometimes two.",
    definition: "Resume length is how many pages your resume spans. For most professionals, the target is one page. Two pages is acceptable for senior professionals with 10+ years of experience. Three or more pages is almost never appropriate for a standard job application (academic CVs are the exception).",
    detail: "The right length depends on your career stage. Recent graduates and early-career professionals should always target one page. Mid-career professionals should also aim for one page but can justify a second page if every bullet adds genuine value. Senior executives can use two pages; anything longer starts to feel like padding. Never expand your resume just to fill space — cut ruthlessly.",
    example: "A 5-year software engineer should have a one-page resume. A VP of Engineering with 15 years of experience can have a two-page resume but should fit it on two full pages, not 1.5.",
    related: ["one-page-resume", "margin", "white-space"],
  },
  {
    slug: "skills",
    term: "Skills (Section)",
    short: "A dedicated resume section listing your hard and soft skills.",
    definition: "The Skills section of a resume lists your hard skills (specific technical abilities) and sometimes soft skills (interpersonal qualities). It's typically a separate section near the bottom or in a sidebar, with skills listed in a clear, scannable format.",
    detail: "The Skills section should include 8 to 15 skills relevant to the job you're applying for. Fewer than 8 looks thin; more than 15 looks padded. Focus on hard skills — specific tools, technologies, methodologies, and languages — because those are the ones ATS systems scan for. Always tailor the Skills section to match the job description.",
    example: "A front-end developer's Skills section might list: \"JavaScript, TypeScript, React, Next.js, HTML5, CSS3, Tailwind, GraphQL, REST APIs, Git, Figma, Jest, Cypress.\"",
    related: ["hard-skills", "soft-skills", "keywords"],
  },
];
